Repository kubeedge/ianvs, pull requests merged in 2024-10, with the labels that each got.

#158 fix: pylint R0917 error
  .github/workflows/main.yaml
Labels: kind/bug, approved, lgtm, size/XS

#127 add Proposal for Large Language Model Edge Benchmark Suite: Implement…
  docs/proposals/scenarios/llm-benchmark-suite/images/fp16.jpg
  docs/proposals/scenarios/llm-benchmark-suite/images/llm-edge-ianvs.png
  docs/proposals/scenarios/llm-benchmark-suite/images/prune.jpg
  docs/proposals/scenarios/llm-benchmark-suite/images/quant.jpg
  docs/proposals/scenarios/llm-benchmark-suite/llm-edge-benchmark-suite.md
Labels: approved, size/L, lgtm, kind/design

#153 add: Heterogeneous Multi-Edge Collaborative Neural Network Inference for High Mobility Scenarios: Base on KubeEdge-Ianvs proposal
  docs/proposals/algorithms/multi-edge-inference/Heterogeneous Multi-Edge Collaborative Neural Network Inference for High Mobility Scenarios.md
  docs/proposals/algorithms/multi-edge-inference/images/benchmarking.png
  docs/proposals/algorithms/multi-edge-inference/images/framework.png
  docs/proposals/algorithms/multi-edge-inference/images/multiedge_inference_method.png
  docs/proposals/algorithms/multi-edge-inference/images/partition_method.png
  docs/proposals/algorithms/multi-edge-inference/images/process.png
Labels: approved, size/L, lgtm, kind/design

#151 OSPP: Implementation of Heterogeneous Multi-Edge Collaborative Neural Network Inference for High Mobility Scenarios
  .gitignore
  core/testcasecontroller/algorithm/paradigm/base.py
  core/testcasecontroller/algorithm/paradigm/multiedge_inference/multiedge_inference.py
  examples/imagenet/multiedge_inference_bench/README.md
  examples/imagenet/multiedge_inference_bench/classification_job_automatic.yaml
  examples/imagenet/multiedge_inference_bench/classification_job_manual.yaml
  examples/imagenet/multiedge_inference_bench/images/auto_result.png
  examples/imagenet/multiedge_inference_bench/images/onnx_version.png
  examples/imagenet/multiedge_inference_bench/images/plot.png
  examples/imagenet/multiedge_inference_bench/images/profiler_results.png
  examples/imagenet/multiedge_inference_bench/images/result.png
  examples/imagenet/multiedge_inference_bench/requirements.txt
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/basemodel.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/classification_algorithm.yaml
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/dataset.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/devices.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/devices.yaml
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/model_cfg.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/models/__init__.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/models/transformers/__init__.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/models/transformers/bert.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/models/transformers/deit.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/models/transformers/vit.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/profiler.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/utils/yaml_files.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/automatic/utils/yaml_types.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/manual/basemodel.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/manual/classification_algorithm.yaml
  examples/imagenet/multiedge_inference_bench/testalgorithms/manual/dataset.py
  examples/imagenet/multiedge_inference_bench/testalgorithms/manual/devices.yaml
  examples/imagenet/multiedge_inference_bench/testalgorithms/manual/devices_one.yaml
  examples/imagenet/multiedge_inference_bench/testenv/accuracy.py
  examples/imagenet/multiedge_inference_bench/testenv/fps.py
  examples/imagenet/multiedge_inference_bench/testenv/peak_memory.py
  examples/imagenet/multiedge_inference_bench/testenv/peak_power.py
  examples/imagenet/multiedge_inference_bench/testenv/testenv.yaml
Labels: kind/feature, size/XXL, approved, lgtm

#144 OSPP: Implementation of Domain-Specific Large Model Benchmarking Based on KubeEdge-Ianvs
  core/common/constant.py
  core/testcasecontroller/algorithm/paradigm/singletask_learning/singletask_learning.py
  core/testenvmanager/dataset/dataset.py
  examples/government/singletask_learning_bench/README.md
  examples/government/singletask_learning_bench/imgs/structure.png
  examples/government/singletask_learning_bench/objective/benchmarkingjob.yaml
  examples/government/singletask_learning_bench/objective/testalgorithms/gen/basemodel.py
  examples/government/singletask_learning_bench/objective/testalgorithms/gen/gen_algorithm.yaml
  examples/government/singletask_learning_bench/objective/testenv/acc.py
  examples/government/singletask_learning_bench/objective/testenv/testenv.yaml
  examples/government/singletask_learning_bench/subjective/benchmarkingjob.yaml
  examples/government/singletask_learning_bench/subjective/testalgorithms/gen/basemodel.py
  examples/government/singletask_learning_bench/subjective/testalgorithms/gen/gen_algorithm.yaml
  examples/government/singletask_learning_bench/subjective/testenv/llm_judgement.py
  examples/government/singletask_learning_bench/subjective/testenv/testenv.yaml
  examples/llm_simple_qa/README.md
  examples/llm_simple_qa/benchmarkingjob.yaml
  examples/llm_simple_qa/testalgorithms/gen/basemodel.py
  examples/llm_simple_qa/testalgorithms/gen/gen_algorithm.yaml
  examples/llm_simple_qa/testalgorithms/gen/op_eval.py
  examples/llm_simple_qa/testenv/acc.py
  examples/llm_simple_qa/testenv/testenv.yaml
  examples/resources/sedna-llm.zip
Labels: kind/feature, size/XXL, approved, lgtm

#150 add Impl for llm edge benchmark suite
  core/testcasecontroller/algorithm/algorithm.py
  core/testcasecontroller/algorithm/paradigm/singletask_learning/singletask_learning.py
  core/testenvmanager/testenv/testenv.py
  examples/llm-edge-benchmark-suite/README.md
  examples/llm-edge-benchmark-suite/single_task_bench/README.md
  examples/llm-edge-benchmark-suite/single_task_bench/benchmarkingjob.yaml
  examples/llm-edge-benchmark-suite/single_task_bench/testalgorithms/algorithm.yaml
  examples/llm-edge-benchmark-suite/single_task_bench/testalgorithms/basemodel.py
  examples/llm-edge-benchmark-suite/single_task_bench/testalgorithms/download_model_modelscope.py
  examples/llm-edge-benchmark-suite/single_task_bench/testenv/latency.py
  examples/llm-edge-benchmark-suite/single_task_bench/testenv/mem_usage.py
  examples/llm-edge-benchmark-suite/single_task_bench/testenv/prefill_latency.py
  examples/llm-edge-benchmark-suite/single_task_bench/testenv/testenv.yaml
  examples/llm-edge-benchmark-suite/single_task_bench/testenv/throughput.py
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/README.md
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/benchmarkingjob.yaml
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testalgorithms/algorithm.yaml
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testalgorithms/basemodel.py
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testalgorithms/download_model_modelscope.py
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testenv/latency.py
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testenv/mem_usage.py
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testenv/prefill_latency.py
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testenv/testenv.yaml
  examples/llm-edge-benchmark-suite/single_task_bench_with_compression/testenv/throughput.py
Labels: kind/feature, approved, lgtm, size/XL

#120 add a proposal of Smart Coding benchmark suite
  docs/proposals/scenarios/Smart_Coding/Smart Coding benchmark suite Proposal.md
  docs/proposals/scenarios/Smart_Coding/Smart Coding benchmark suite Proposal_zh.md
  docs/proposals/scenarios/Smart_Coding/image/change_part.png
  docs/proposals/scenarios/Smart_Coding/image/data_process_change.png
  docs/proposals/test-reports/Smart Coding benchmark suite Proposal_zh.md
Labels: approved, size/L, lgtm, kind/design

#154 [OSPP]: Personalized LLM Agent based on KubeEdge-Ianvs Cloud-Edge Collaboration
  docs/proposals/algorithms/single-task-learning/Personalized LLM Agent based on KubeEdge-Ianvs Cloud-Edge Collaboration.md
  docs/proposals/algorithms/single-task-learning/images/Q2A_task_plan.png
  docs/proposals/algorithms/single-task-learning/images/agent-overview.png
  docs/proposals/algorithms/single-task-learning/images/bert_score.png
  docs/proposals/algorithms/single-task-learning/images/continual_llm_agent.png
  docs/proposals/algorithms/single-task-learning/images/llm_agent_ianvs.png
  docs/proposals/algorithms/single-task-learning/images/personalized_agent.png
  examples/llm-agent/config/config.json
  examples/llm-agent/config/train_config.json
  examples/llm-agent/singletask_learning_bench/README.md
  examples/llm-agent/singletask_learning_bench/benchmarkingjob.yaml
  examples/llm-agent/singletask_learning_bench/testalgorithms/basemodel.py
  examples/llm-agent/singletask_learning_bench/testalgorithms/test_algorithm.yaml
  examples/llm-agent/singletask_learning_bench/testenv/rouge.py
  examples/llm-agent/singletask_learning_bench/testenv/testenv.yaml
Labels: approved, lgtm, size/XL

#159 OSPP: Smart Coding benchmark suite: built on KubeEdge-lanvs
  core/testenvmanager/dataset/dataset.py
  docs/guides/images/ianvs_arch.png
  examples/smart_coding/smart_coding_learning_bench/README.md
  examples/smart_coding/smart_coding_learning_bench/comment/benchmarkingjob.yaml
  examples/smart_coding/smart_coding_learning_bench/comment/testalgorithms/gen/basemodel.py
  examples/smart_coding/smart_coding_learning_bench/comment/testalgorithms/gen/gen_algorithm.yaml
  examples/smart_coding/smart_coding_learning_bench/comment/testenv/llm_judgement.py
  examples/smart_coding/smart_coding_learning_bench/comment/testenv/testenv.yaml
  examples/smart_coding/smart_coding_learning_bench/imgs/img.png
  examples/smart_coding/smart_coding_learning_bench/issue/benchmarkingjob.yaml
  examples/smart_coding/smart_coding_learning_bench/issue/testalgorithms/gen/basemodel.py
  examples/smart_coding/smart_coding_learning_bench/issue/testalgorithms/gen/gen_algorithm.yaml
  examples/smart_coding/smart_coding_learning_bench/issue/testenv/llm_judgement.py
  examples/smart_coding/smart_coding_learning_bench/issue/testenv/testenv.yaml
Labels: kind/feature, size/XXL, approved, lgtm
