Repository kubeedge/ianvs, pull requests merged in 2025-04, with the labels that each got.

#185 Proposal for LFX:issue#178 Enhance Dependency Management and Documentation for Ianvs
  docs/proposals/chore/enhance_dependency_management_and_documentation_for_ianvs.md
Labels: approved, size/L, lgtm, kind/design

#186 add: LFX government proposal
  docs/proposals/scenarios/government_affairs/assets/data_generate.png
  docs/proposals/scenarios/government_affairs/assets/data_process.png
  docs/proposals/scenarios/government_affairs/assets/ianvs_flowchart.png
  docs/proposals/scenarios/government_affairs/assets/ianvs_structure.png
  docs/proposals/scenarios/government_affairs/assets/singletasklearning_change.png
  docs/proposals/scenarios/government_affairs/government_affairs.md
  docs/proposals/scenarios/government_affairs/government_affairs_zh.md
Labels: approved, kind/documentation, lgtm, size/XL

#179 Add Speculative Decoding Support for LLM under Cloud-Edge Collaborative Scenario
  examples/cloud-edge-collaborative-inference-for-llm/README.md
  examples/cloud-edge-collaborative-inference-for-llm/assets/Architecture.png
  examples/cloud-edge-collaborative-inference-for-llm/assets/image-20240926143857223.png
  examples/cloud-edge-collaborative-inference-for-llm/benchmarkingjob.yaml
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/edge_model.py
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/models/__init__.py
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/models/api_llm.py
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/models/base_llm.py
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/models/eagle_llm.py
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/models/huggingface_llm.py
  examples/cloud-edge-collaborative-inference-for-llm/testalgorithms/query-routing/test_queryrouting.yaml
  examples/cloud-edge-collaborative-inference-for-llm/testenv/testenv.yaml
Labels: kind/feature, approved, size/L, lgtm

#195 ubuntu runner in ci checks updated to use 22.04 instead of 20.04
  .github/workflows/codeql-analysis.yml
  .github/workflows/fossa.yaml
  .github/workflows/main-doc.yaml
  .github/workflows/main.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#189 Readme moved from fault detection to fault_detection
  examples/pcb-aoi/singletask_learning_bench/fault_detection/README.md
Labels: approved, lgtm, size/XS

#190 Ianvs new release note v0.3.0 added to docs
  docs/roadmap.md
Labels: approved, size/M, kind/documentation, lgtm
