Repository kubeedge/ianvs, pull requests merged in 2025-09, with the labels that each got.

#256 IndustrialEi Pose Estimation Implementation
  examples/industrialEI/pose-estimation-llio/README.md
  examples/industrialEI/pose-estimation-llio/assets/ianvs-architecture.drawio.svg
  examples/industrialEI/pose-estimation-llio/assets/lidartrajectories.png
  examples/industrialEI/pose-estimation-llio/assets/point_cloud.png
  examples/industrialEI/pose-estimation-llio/assets/pose-estimation-architecture.drawio.svg
  examples/industrialEI/pose-estimation-llio/benchmarkingjob.yaml
  examples/industrialEI/pose-estimation-llio/requirements.txt
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/__init__.py
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/basemodel.py
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/kitti/__init__.py
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/kitti/calib.py
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/kitti/dataloader.py
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/llio_algorithm.yaml
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/llio_estimator.py
  examples/industrialEI/pose-estimation-llio/testalgorithms/llio_fusion/utils.py
  examples/industrialEI/pose-estimation-llio/testenv/orientation_error.py
  examples/industrialEI/pose-estimation-llio/testenv/position_error.py
  examples/industrialEI/pose-estimation-llio/testenv/testenv.yaml
  examples/industrialEI/pose-estimation-llio/testenv/trajectory_consistency.py
Labels: size/XXL, approved, lgtm

#260 Proposal:Embodied Intelligence Benchmarking Framework for Industrial Manufacturing with KubeEdge
  docs/proposals/scenarios/Industrial manufacturing/Palletizing.md
  docs/proposals/scenarios/Industrial manufacturing/Palletizing_real.png
  docs/proposals/scenarios/Industrial manufacturing/Palletizing_sim.png
  docs/proposals/scenarios/Industrial manufacturing/Single_Task_Learning.png
  docs/proposals/scenarios/Industrial manufacturing/YOLOv8_latest.png
  docs/proposals/scenarios/Industrial manufacturing/camera_capture.png
  docs/proposals/scenarios/Industrial manufacturing/flow_chart.png
  docs/proposals/scenarios/Industrial manufacturing/ianvs.png
Labels: approved, size/L, kind/documentation, lgtm

#227 a proposal for the project Physically Consistent and Interactable Indoor Simulation Scene Generation
  docs/proposals/scenarios/phys-scene-gen/images/ianvs_arch.png
  docs/proposals/scenarios/phys-scene-gen/images/physcene_arch.png
  docs/proposals/scenarios/phys-scene-gen/phys_scene_gen_proposal.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design
